PREFIX ex: <http://example.org/>

SELECT ?id ?attr ?val WHERE {
   ?row ex:ID ?id .
   ?row ?predicate ?val .
   FILTER(?predicate != ex:ID)
   BIND(STRAFTER(STR(?predicate), "http://example.org/") AS ?attr)
}